# Generated by Django 4.2.27 on 2026-02-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('ideas', 'Ideas'), ('important', 'Important')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
