# Generated by Django 4.2.27 on 2026-04-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('option', models.CharField(choices=[('Personal', 'Personal'), ('Work / Professional', 'Work / Professional'), ('Home / Chores', 'Home / Chores'), ('Study / Education', 'Study / Education'), ('Health / Fitness', 'Health / Fitness'), ('Shopping / Errands', 'Shopping / Errands'), ('Finance / Bills', 'Finance / Bills'), ('Social / Relationships', 'Social / Relationships'), ('Travel / Leisure', 'Travel / Leisure'), ('Events / Appointments', 'Events / Appointments'), ('Goals / Projects', 'Goals / Projects'), ('Hobbies / Creativity', 'Hobbies / Creativity'), ('Self-improvement', 'Self-improvement'), ('Community / Volunteering', 'Community / Volunteering'), ('Miscellaneous / Urgent', 'Miscellaneous / Urgent')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
