# Generated by Django 4.2.27 on 2026-02-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
