# Generated by Django 4.2.27 on 2026-02-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_pinned',
        ),
    ]
