# Generated by Django 6.0.1 on 2026-01-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='options',
            new_name='option',
        ),
    ]
