# Generated by Django 6.0.1 on 2026-01-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_options_task_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.CharField(choices=[('option1', 'Work'), ('option2', 'Study'), ('option3', 'Travel'), ('option4', 'Family'), ('option5', 'Shopping'), ('option6', 'Exercise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
