# Generated by Django 4.2.27 on 2026-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_task_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.CharField(choices=[('option1', 'Personal'), ('option2', 'Work / Professional'), ('option3', 'Home / Chores'), ('option4', 'Study / Education'), ('option5', 'Health / Fitness'), ('option6', 'Shopping / Errands'), ('option7', 'Finance / Bills'), ('option8', 'Social / Relationships'), ('option9', 'Travel / Leisure'), ('option10', 'Events / Appointments'), ('option11', 'Goals / Projects'), ('option12', 'Hobbies / Creativity'), ('option13', 'Self-improvement'), ('option14', 'Community / Volunteering'), ('option15', 'Miscellaneous / Urgent')], max_length=50),
        ),
    ]
