# Generated by Django 4.2.27 on 2026-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_task_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work / Professional', 'Work / Professional'), ('Home / Chores', 'Home / Chores'), ('Study / Education', 'Study / Education'), ('Health / Fitness', 'Health / Fitness'), ('Shopping / Errands', 'Shopping / Errands'), ('Finance / Bills', 'Finance / Bills'), ('Social / Relationships', 'Social / Relationships'), ('Travel / Leisure', 'Travel / Leisure'), ('Events / Appointments', 'Events / Appointments'), ('Goals / Projects', 'Goals / Projects'), ('Hobbies / Creativity', 'Hobbies / Creativity'), ('Self-improvement', 'Self-improvement'), ('Community / Volunteering', 'Community / Volunteering'), ('Miscellaneous / Urgent', 'Miscellaneous / Urgent')], max_length=50),
        ),
    ]
